"""GitHub Actions workflow scaffolding (#99) + PR-comment / code-scanning wiring (#116).

``vibeguard setup github-actions`` generates a ready-to-commit
``.github/workflows/vibeguard.yml`` so a new user gets a working PR gate in one
command instead of hand-assembling YAML. The generated workflow wires three PR
surfaces in a single job:

1. **SARIF upload** → inline code-scanning annotations on the PR diff.
2. **PR comment** → one summary comment, updated in place on each push (no spam).
3. **Gate** → fails the PR on findings at/above ``--fail-on``.

It installs VibeGuard from PyPI (no action tag to drift — see
``scripts/check_doc_versions.py``) and posts the comment with
``actions/github-script``, so **no networking is added to the VibeGuard core**
(see #93 non-goals — "no network-dependent checks").

The CLI surface is ``vibeguard setup github-actions`` (see :mod:`vibeguard.cli`);
the logic lives here so it is unit-testable without spawning the CLI, mirroring
:mod:`vibeguard.scaffold`.

Third-party actions in the generated workflow are pinned to full commit SHAs
with a trailing version comment (#190), matching the supply-chain standard
VibeGuard's own workflows hold themselves to. These pins are string literals, so
this repo's Dependabot cannot bump them — refresh them by hand when the pinned
action cuts a release (see ``docs/release-checklist.md``).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from vibeguard.config import render_config_body
from vibeguard.models import Severity
from vibeguard.policies import load_policy_pack
from vibeguard.reporters.markdown import PR_COMMENT_MARKER

# Repo-relative target paths the generator writes.
WORKFLOW_REL = Path(".github/workflows/vibeguard.yml")
CONFIG_REL = Path("vibeguard.yaml")

# Accepted ``--fail-on`` values (the severity ladder).
VALID_FAIL_ON: tuple[str, ...] = tuple(s.value for s in Severity)

# Safe default when neither the flag nor a policy pack specify a threshold.
DEFAULT_FAIL_ON = "high"


class SetupError(ValueError):
    """Raised for invalid input or a refused overwrite."""


@dataclass
class SetupResult:
    """Outcome of a setup run (mirrors :class:`vibeguard.scaffold.ScaffoldResult`)."""

    created: list[Path] = field(default_factory=list)
    skipped: list[Path] = field(default_factory=list)
    rendered: dict[Path, str] = field(default_factory=dict)
    dry_run: bool = False


# ``__FAIL_ON__`` and ``__MARKER__`` are substituted by :func:`render_workflow`.
# Not an f-string: the body is full of ``${{ ... }}`` GitHub expressions that
# would otherwise need brace-doubling on every line.
_WORKFLOW_TEMPLATE = """\
# Generated by `vibeguard setup github-actions`.
#
# VibeGuard — the deterministic pre-merge safety gate for AI-generated diffs.
# Docs: https://github.com/dgenio/vibeguard/blob/main/docs/github-actions.md
#
# One job wires three PR surfaces:
#   1. SARIF upload → inline code-scanning annotations on the diff
#   2. PR comment   → one summary comment, updated in place (no spam)
#   3. Gate         → fails the PR on findings at/above `--fail-on`
name: VibeGuard
on:
  pull_request:

# Least-privilege: read code, write the PR comment, upload SARIF.
permissions:
  contents: read
  pull-requests: write
  security-events: write

concurrency:
  group: vibeguard-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vibeguard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          fetch-depth: 0  # required for --diff (needs the merge base)

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: "3.11"
          cache: pip

      - name: Install VibeGuard
        run: pip install vibeguard-gate

      # Inline code-scanning annotations on the PR diff. `--base` pins the diff
      # to the PR's target branch so scoping matches the merge base.
      - name: Scan (SARIF)
        run: vibeguard scan --diff --base "origin/${{ github.base_ref }}" --sarif --output vibeguard.sarif
        continue-on-error: true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@b7351df727350dca84cb9d725d57dcf5bc82ba26  # v3.37.1
        with:
          sarif_file: vibeguard.sarif
          category: vibeguard

      # Gate + PR-comment body. `set +e` so a failing gate still posts the
      # comment; the exit code is preserved and re-applied at the end.
      - name: Run gate
        id: gate
        run: |
          set +e
          vibeguard gate --diff --base "origin/${{ github.base_ref }}" --fail-on __FAIL_ON__ --pr-comment --output vibeguard-comment.md
          echo "exit-code=$?" >> "$GITHUB_OUTPUT"

      - name: Post / update PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b  # v7.1.0
        with:
          script: |
            const fs = require("fs");
            const body = fs.readFileSync("vibeguard-comment.md", "utf8");
            const marker = "__MARKER__";
            // Page through every comment (listComments caps at 30/page) so the
            // marker comment is still found on long PRs, and only match our own
            // bot comment so a user echoing the marker can't be overwritten.
            const comments = await github.paginate(github.rest.issues.listComments, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100,
            });
            const existing = comments.find(
              (c) => c.user?.login === "github-actions[bot]" && c.body && c.body.includes(marker)
            );
            if (existing) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existing.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }

      # Re-apply the gate's exit code so the PR check reflects the result.
      - name: Enforce gate
        run: exit ${{ steps.gate.outputs.exit-code }}
"""


def validate_fail_on(fail_on: str) -> None:
    """Raise :class:`SetupError` unless ``fail_on`` is a known severity."""
    if fail_on not in VALID_FAIL_ON:
        raise SetupError(
            f"Invalid --fail-on {fail_on!r}: choose one of {', '.join(VALID_FAIL_ON)}."
        )


def resolve_fail_on(fail_on: str | None, pack_data: dict | None) -> str:
    """Pick the gate threshold: explicit flag > policy pack > safe default.

    ``pack_data`` is the already-loaded policy-pack dict (or ``None``).
    """
    if fail_on is not None:
        validate_fail_on(fail_on)
        return fail_on
    if pack_data is not None:
        packed = pack_data.get("fail_on")
        if isinstance(packed, str):
            validate_fail_on(packed)
            return packed
    return DEFAULT_FAIL_ON


def render_workflow(fail_on: str) -> str:
    """Render the workflow YAML for the given gate threshold."""
    return _WORKFLOW_TEMPLATE.replace("__FAIL_ON__", fail_on).replace(
        "__MARKER__", PR_COMMENT_MARKER
    )


def setup_github_actions(
    *,
    root: Path,
    fail_on: str | None = None,
    policy_pack: str | None = None,
    with_config: bool = False,
    force: bool = False,
    dry_run: bool = False,
) -> SetupResult:
    """Generate the GitHub Actions PR-gate workflow (and optionally a config).

    Always renders ``.github/workflows/vibeguard.yml``. Also renders
    ``vibeguard.yaml`` when ``with_config`` is set or a ``policy_pack`` is named
    (a pack only takes effect through a config that references it).

    Returns a :class:`SetupResult`. Raises :class:`SetupError` on an invalid
    ``--fail-on``, an unknown policy pack, or an existing target file when
    ``force`` is not set.
    """
    pack_data: dict | None = None
    if policy_pack is not None:
        try:
            pack_data = load_policy_pack(policy_pack)
        except ValueError as exc:  # UnknownPolicyPackError
            raise SetupError(str(exc)) from exc

    fail_on_resolved = resolve_fail_on(fail_on, pack_data)

    targets: dict[Path, str] = {root / WORKFLOW_REL: render_workflow(fail_on_resolved)}
    if with_config or policy_pack is not None:
        targets[root / CONFIG_REL] = render_config_body(policy_pack)

    result = SetupResult(dry_run=dry_run)

    # Refuse to clobber any existing target up front (check all before writing
    # any) unless --force was passed — same posture as `vibeguard dev new-rule`.
    if not force and not dry_run:
        existing = [p for p in targets if p.exists()]
        if existing:
            rels = ", ".join(str(p) for p in existing)
            raise SetupError(
                f"Refusing to overwrite existing file(s): {rels}. Pass --force to overwrite."
            )

    for path, content in targets.items():
        result.rendered[path] = content
        if dry_run:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        result.created.append(path)

    return result
